### ISSUE TITLE
SSO entity-id seems not configurable

### ISSUE THREAD

**Issue by babantax** [reportportal/service-authorization#232]
Good morning,
I´m facing this situation:
I configured SSO SAML integration with azure in our STG environment for testing purpose. It is working properly 
When I started to configure the azure integration for PROD, the entity-id with value 'report.portal.sp.id' was already declared for the STG env and I can not re-use.
Is there any way to modify this entity-id value in my RP PROD deployment?
![image](https://user-images.githubusercontent.com/52815118/202661750-9b1094fb-0566-4bc1-acb8-f83d3faf09cd.png)
For example to set it at 'report.portal.prd.sp.id'
Thanks a lot

**Comment by luis-periquito** [comment]
I was looking for the same question and saw your post. 

Which lead me to think on the variable loading and found that if you set the environment variable `RP_AUTH_SAML_ENTITY-ID` it will override the default.

so now my docker compose is:
```
  uat:
    image: reportportal/service-authorization:5.7.3
    environment:
      - RP_AUTH_SAML_ENTITY-ID=report.portal.sp.id.prd
```

Now I have both versions of report portal authenticating to the same Azure environment.
